import Link from 'next/link'
import { prisma } from '@/lib/prisma'
import { PracticeSetRunner } from './practice-set-runner'
import { resolveActiveUser } from '@/lib/user'

function parseJson<T>(value: string | null | undefined): T | null {
  if (!value) return null
  try {
    return JSON.parse(value) as T
  } catch {
    return null
  }
}

type ExerciseQuestionPreview = {
  type?: string
  question?: string
  prompt?: string
}

type ExerciseContentPreview = {
  title?: string
  description?: string
  difficulty?: string
  type?: string
  questions?: ExerciseQuestionPreview[]
}

export default async function PracticeLabPage() {
  const user = await resolveActiveUser()

  const exerciseSets = await prisma.exerciseSet.findMany({
    orderBy: { createdAt: 'desc' },
    take: 18,
    include: {
      lesson: {
        include: {
          module: {
            include: {
              program: true,
            },
          },
        },
      },
      attempts: {
        where: { userId: user.id },
        orderBy: { createdAt: 'desc' },
        take: 1,
      },
    },
  })

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5">
          <div>
            <p className="text-sm text-gray-500">Practice Lab</p>
            <h1 className="text-2xl font-bold text-gray-900">Targeted Workbooks</h1>
          </div>
          <div className="flex gap-2">
            <Link
              href="/programs"
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700"
            >
              Programs
            </Link>
            <Link href="/review" className="rounded-lg bg-primary px-3 py-2 text-sm font-medium text-white">
              Review Center
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-6xl px-6 py-6">
        <div className="mb-4 rounded-xl border bg-white p-4 text-sm text-gray-600">
          Completed lessons publish exercises here automatically. Students can regenerate similar sets from lesson pages or retake previous attempts.
        </div>

        {exerciseSets.length === 0 ? (
          <div className="rounded-xl border bg-white p-8 text-center text-gray-600">
            No practice sets available yet. Build at least one lesson to unlock workbook exercises.
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {exerciseSets.map((set) => {
              const content = parseJson<ExerciseContentPreview>(set.contentJson)
              const questions = content?.questions ?? []
              const latestAttempt = set.attempts[0]

              return (
                <article key={set.id} className="rounded-xl border bg-white p-4 shadow-sm">
                  <p className="text-xs text-gray-500">
                    {set.lesson.module.program.topic} • Module {set.lesson.module.index + 1} • Lesson {set.lesson.index + 1}
                  </p>
                  <h2 className="mt-1 text-base font-semibold text-gray-900">
                    {content?.title || `${set.lesson.title} Practice Set`}
                  </h2>
                  <p className="mt-1 text-xs text-gray-600">
                    {content?.description || 'Practice set generated by Exercise Generator agent.'}
                  </p>

                  <div className="mt-3 flex flex-wrap gap-2 text-[11px]">
                    <span className="rounded bg-gray-100 px-2 py-1 text-gray-700">
                      {set.difficulty.toLowerCase()}
                    </span>
                    <span className="rounded bg-gray-100 px-2 py-1 text-gray-700">
                      {set.type.toLowerCase()}
                    </span>
                    <span className="rounded bg-gray-100 px-2 py-1 text-gray-700">
                      {questions.length} question(s)
                    </span>
                  </div>

                  {questions.length > 0 && (
                    <ul className="mt-3 space-y-1 rounded-md border border-gray-200 bg-gray-50 p-2">
                      {questions.slice(0, 3).map((question, index) => (
                        <li key={`${set.id}-q-${index}`} className="text-xs text-gray-700">
                          <span className="font-medium text-gray-500">{question.type || 'item'}:</span>{' '}
                          {question.question || question.prompt || 'Question preview unavailable'}
                        </li>
                      ))}
                    </ul>
                  )}

                  {latestAttempt && (
                    <p className="mt-3 rounded bg-blue-50 px-2 py-1 text-xs text-blue-700">
                      Last attempt score: {latestAttempt.score ?? 'Pending grading'}
                    </p>
                  )}

                  <div className="mt-3 flex gap-2">
                    <Link
                      href={`/lessons/${set.lessonId}`}
                      className="flex-1 rounded-lg border border-gray-300 px-3 py-2 text-center text-xs font-semibold text-gray-700"
                    >
                      Open Lesson
                    </Link>
                  </div>

                  <PracticeSetRunner
                    exerciseSetId={set.id}
                    lessonId={set.lessonId}
                    title={content?.title || `${set.lesson.title} Practice Set`}
                    description={content?.description || 'Practice set generated by Exercise Generator agent.'}
                    questions={questions}
                  />
                </article>
              )
            })}
          </div>
        )}
      </main>
    </div>
  )
}
