import Link from 'next/link'
import { Dumbbell, FileText, Sparkles } from 'lucide-react'
import { prisma } from '@/lib/prisma'
import { PracticeSetRunner } from './practice-set-runner'
import { resolveActiveUser } from '@/lib/user'
import { AppShell, Badge, Card, CardContent, CardHeader, CardTitle, EmptyState, PageHeader } from '@/components/ui'
import { productNav } from '@/lib/app-navigation'

function parseJson<T>(value: string | null | undefined): T | null {
  if (!value) return null
  try {
    return JSON.parse(value) as T
  } catch {
    return null
  }
}

type ExerciseQuestionPreview = {
  type?: string
  question?: string
  prompt?: string
}

type ExerciseContentPreview = {
  title?: string
  description?: string
  difficulty?: string
  type?: string
  questions?: ExerciseQuestionPreview[]
}

export default async function PracticeLabPage() {
  const user = await resolveActiveUser()

  const exerciseSets = await prisma.exerciseSet.findMany({
    orderBy: { createdAt: 'desc' },
    take: 18,
    include: {
      lesson: {
        include: {
          module: {
            include: {
              program: true,
            },
          },
        },
      },
      attempts: {
        where: { userId: user.id },
        orderBy: { createdAt: 'desc' },
        take: 1,
      },
    },
  })

  return (
    <AppShell nav={productNav} currentPath="/practice" status="needs-input">
      <div className="space-y-6">
        <PageHeader
          title="Practice"
          subtitle="Focused workbook sets generated from completed lessons."
          actions={
            <Link
              href="/review"
              className="inline-flex h-10 items-center rounded-xl border border-border px-4 text-sm font-medium text-foreground hover:bg-muted"
            >
              Open review center
            </Link>
          }
        />

        <Card className="subtle-gradient">
          <CardContent className="flex items-start gap-3 p-4">
            <span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-muted text-muted-foreground">
              <Sparkles className="h-4 w-4" />
            </span>
            <p className="text-sm text-muted-foreground">
              Exercise sets update automatically as lessons complete. Attempts are graded and recorded instantly.
            </p>
          </CardContent>
        </Card>

        {exerciseSets.length === 0 ? (
          <EmptyState
            icon={<Dumbbell className="h-5 w-5" />}
            title="No practice sets yet"
            description="Build at least one lesson to unlock generated workbook exercises."
          />
        ) : (
          <section className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            {exerciseSets.map((set) => {
              const content = parseJson<ExerciseContentPreview>(set.contentJson)
              const questions = content?.questions ?? []
              const latestAttempt = set.attempts[0]

              return (
                <Card key={set.id} className="overflow-hidden">
                  <CardHeader className="space-y-2">
                    <p className="text-xs text-muted-foreground">
                      {set.lesson.module.program.topic} • Module {set.lesson.module.index + 1} • Lesson {set.lesson.index + 1}
                    </p>
                    <CardTitle className="text-base">{content?.title || `${set.lesson.title} Practice Set`}</CardTitle>
                    <p className="text-xs text-muted-foreground">
                      {content?.description || 'Practice set generated by Exercise Generator agent.'}
                    </p>
                    <div className="flex flex-wrap gap-2">
                      <Badge variant="muted">{set.difficulty.toLowerCase()}</Badge>
                      <Badge variant="muted">{set.type.toLowerCase()}</Badge>
                      <Badge variant="muted">{questions.length} question(s)</Badge>
                    </div>
                  </CardHeader>

                  <CardContent className="space-y-3">
                    {questions.length > 0 ? (
                      <ul className="space-y-1 rounded-xl border border-border/70 bg-muted/30 p-2">
                        {questions.slice(0, 3).map((question, index) => (
                          <li key={`${set.id}-q-${index}`} className="text-xs text-muted-foreground">
                            <span className="font-medium text-foreground/80">{question.type || 'item'}:</span>{' '}
                            {question.question || question.prompt || 'Question preview unavailable'}
                          </li>
                        ))}
                      </ul>
                    ) : null}

                    {latestAttempt ? (
                      <Badge variant={latestAttempt.score !== null && latestAttempt.score >= 70 ? 'success' : latestAttempt.score === null ? 'muted' : 'warn'}>
                        Last attempt score: {latestAttempt.score ?? 'Pending grading'}
                      </Badge>
                    ) : null}

                    <Link
                      href={`/lessons/${set.lessonId}`}
                      className="inline-flex h-9 items-center rounded-lg border border-border px-3 text-xs font-medium text-foreground hover:bg-muted"
                    >
                      <FileText className="mr-1.5 h-3.5 w-3.5" />
                      Open lesson
                    </Link>

                    <PracticeSetRunner
                      exerciseSetId={set.id}
                      lessonId={set.lessonId}
                      title={content?.title || `${set.lesson.title} Practice Set`}
                      description={content?.description || 'Practice set generated by Exercise Generator agent.'}
                      questions={questions}
                    />
                  </CardContent>
                </Card>
              )
            })}
          </section>
        )}
      </div>
    </AppShell>
  )
}
