// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admissions" | "/assessments/[id]" | "/dashboard" | "/gradebook" | "/lessons/[id]" | "/practice" | "/programs" | "/programs/[id]" | "/programs/[id]/calendar" | "/review"
type AppRouteHandlerRoutes = "/api/admissions/answer" | "/api/admissions/start" | "/api/assessments/submit" | "/api/daily-plan" | "/api/exercises/submit" | "/api/jobs" | "/api/jobs/[id]" | "/api/lessons/[lessonId]/resources" | "/api/programs/[id]" | "/api/programs/generate" | "/api/programs/generate/events/[jobId]" | "/api/programs/generate/recover/[jobId]" | "/api/programs/generate/retry/[jobId]" | "/api/programs/generate/status/[jobId]" | "/api/programs/generate/stream" | "/api/tutor/ask"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admissions": {}
  "/api/admissions/answer": {}
  "/api/admissions/start": {}
  "/api/assessments/submit": {}
  "/api/daily-plan": {}
  "/api/exercises/submit": {}
  "/api/jobs": {}
  "/api/jobs/[id]": { "id": string; }
  "/api/lessons/[lessonId]/resources": { "lessonId": string; }
  "/api/programs/[id]": { "id": string; }
  "/api/programs/generate": {}
  "/api/programs/generate/events/[jobId]": { "jobId": string; }
  "/api/programs/generate/recover/[jobId]": { "jobId": string; }
  "/api/programs/generate/retry/[jobId]": { "jobId": string; }
  "/api/programs/generate/status/[jobId]": { "jobId": string; }
  "/api/programs/generate/stream": {}
  "/api/tutor/ask": {}
  "/assessments/[id]": { "id": string; }
  "/dashboard": {}
  "/gradebook": {}
  "/lessons/[id]": { "id": string; }
  "/practice": {}
  "/programs": {}
  "/programs/[id]": { "id": string; }
  "/programs/[id]/calendar": { "id": string; }
  "/review": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
