// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admissions">> = Specific
  const handler = {} as typeof import("../../src/app/admissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assessments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assessments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/assessments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gradebook/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gradebook">> = Specific
  const handler = {} as typeof import("../../src/app/gradebook/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/lessons/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lessons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/lessons/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/practice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice">> = Specific
  const handler = {} as typeof import("../../src/app/practice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programs/[id]/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/[id]/calendar">> = Specific
  const handler = {} as typeof import("../../src/app/programs/[id]/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/programs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs">> = Specific
  const handler = {} as typeof import("../../src/app/programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../src/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admissions/answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admissions/answer">> = Specific
  const handler = {} as typeof import("../../src/app/api/admissions/answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admissions/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admissions/start">> = Specific
  const handler = {} as typeof import("../../src/app/api/admissions/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assessments/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assessments/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/assessments/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/daily-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/daily-plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/daily-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/exercises/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/exercises/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/exercises/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/lessons/[lessonId]/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lessons/[lessonId]/resources">> = Specific
  const handler = {} as typeof import("../../src/app/api/lessons/[lessonId]/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/events/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate/events/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/events/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/recover/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate/recover/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/recover/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/retry/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate/retry/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/retry/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/status/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate/status/[jobId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/status/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/programs/generate/stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/programs/generate/stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/programs/generate/stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tutor/ask/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tutor/ask">> = Specific
  const handler = {} as typeof import("../../src/app/api/tutor/ask/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
